### ISSUE TITLE
NoMethodError: undefined method `gsub!' for nil:NilClass

### ISSUE THREAD

**Issue by asjer** [simpleanalytics/rubyonrails-plugin#13]
Hi,

I keep getting ``NoMethodError: undefined method `gsub!' for nil:NilClass`` on this line:

https://github.com/simpleanalytics/rubyonrails-plugin/blob/53de7d26bcefc31942b0773766de7dc753cb7a31/lib/simple_analytics_rails/middleware/javascript_injection.rb#L23

Any idea what could be the issue here? Thanks!

**Comment by adriaanvanrossum** [comment]
Let me ask @MikeRogers0, do you know what this could be?

**Comment by adriaandotcom** [comment]
This is now fixed by @ParamagicDev in #15.

See version 3.0.1 at https://rubygems.org/gems/simple_analytics_rails
